### ISSUE TITLE
[LuceneSearch2] Implement Category Based Search

### ISSUE THREAD

**Issue by solverat** [dachcom-digital/pimcore-lucene-search#33]
- respect categories meta tag, if available.
- allow multiple categories
- update readme.md and provide frontend category selection sample

## Configuration
```yaml
lucene_search:
    categories:
        - {id: 1, label: 'Category 1'}
        - {id: 2, label: 'Category 2'}
```
## View
```html
{% if lucene_search_crawler_active() %}
      <meta name="lucene-search:categories">1,2</head>
{% endif %}
```
