### ISSUE TITLE
[LuceneSearch2] refacture config style

### ISSUE THREAD

**Issue by solverat** [dachcom-digital/pimcore-lucene-search#37]
use a more generic config style:

instead of 
```yaml
restriction:ignore: true
restriction:class: ~
restriction:method: ~
```
use
```yaml
restriction:
    ignore: true
    class: ~
    method: ~
```
