### ISSUE TITLE
New Install - Pimcore 5

### ISSUE THREAD

**Issue by ritunrtc** [dachcom-digital/pimcore-lucene-search#47]
I installed for Pimcore 5 using composer . Activated  using extension manager
but can't get the crawler to start.

Keep getting error :
  no valid task iterators defined!

I start the crawler with :
php bin/console lucenesearch:crawl   -v

Any idea what could be going wrong ?

Thanks!

**Comment by nahilep** [comment]
I am having the exact same problem. Only thing different is that I am also using the -f option:
php bin/console lucenesearch:crawl -f -v

**Comment by solverat** [comment]
This happens if the bundle is not configured. Please add a configuration file, for example:
```yaml
lucene_search:
    enabled: true
    sitemap:
        render: false
    fuzzy_search_results: false
    search_suggestion: true
    seeds:
        - 'http://your-domain.dev'
    filter:
        valid_links:
            - '@^http://your-domain.dev.*@i'
    view:
        max_per_page: 10
    crawler:
        content_max_size: 4
        content_start_indicator: '<!-- main-content -->'
        content_end_indicator: '<!-- /main-content -->'
```
