### ISSUE TITLE
Empty result list

### ISSUE THREAD

**Issue by danielerne** [dachcom-digital/pimcore-lucene-search#59]
Hi

We configured lucene search according to the documentation. The crawler has finished successfully and the search template was added with following code:

`<?= $this->actions()->render(new \Symfony\Component\HttpKernel\Controller\ControllerReference('LuceneSearchBundle:List:getResult')); ?>`

But when we add /search?p=test nothing is shown in the list. We only get empty divs generated by the lucene search layout.

Did we forgot something?

Our config is:
```
lucene_search:
    enabled: true
    sitemap:
        render: false
    fuzzy_search_results: false
    search_suggestion: true
    seeds:
        - 'http://domain-xy.com'
    filter:
        valid_links:
            - '@^http://domain-xy.com.*@i'
    view:
        max_per_page: 10
    crawler:
        content_max_size: 4
    locale:
        ignore_language: true
```
