### ISSUE TITLE
Multiple Databases 

### ISSUE THREAD

**Issue by solverat** [dachcom-digital/pimcore-lucene-search#76]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

- Implement a dedicated Lucene Database for each seed. This allows us to separate large sites. Database should be configured in seed config. If no database has been specified, add data to a `default` storage.
- change `seeds` array node to a sub config nodes.
- `own_host_only` and `allow_subdomains` should be configurable for each seed node.

## LS 2.0.0
```yml
lucene_search:
    seeds:
        - 'http://www.domain.com'
```

## LS 3.0.0
```yml
lucene_search:
    seeds:
        - { seed: 'http://www.foo.com', own_host_only: true, allow_subdomains: false, database: 'alpha' }
        - { seed: 'http://www.bar.com', own_host_only: false, allow_subdomains: true, database: 'beta' }
```
