### ISSUE TITLE
https 301 redirect

### ISSUE THREAD

**Issue by paulboenisch** [dachcom-digital/pimcore-lucene-search#89]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

There are no pages crawled if https redirect present.

**Comment by Cruiser13** [comment]
I forgot how I solved this issue earlier so I'm leaving a comment here to remember it next time.
You can use https redirects but you have to allow the scheme. Sample config.yml:
```
lucene_search:
    enabled: true
    allowed_schemes: ['https']
    seeds:
        - 'https://yourdomain.com/'
    filter:
        valid_links:
            - '@^https://yourdomain.com.*@i'
    view:
        max_per_page: 10
    crawler:
        content_max_size: 4
        content_start_indicator: '<body>'
        content_end_indicator: '</body>'
```
